/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.dotcontrolltec;

import com.fasterxml.jackson.databind.ser.std.StdKeySerializers;
import com.mycompany.dotcontrolltec.computadores.Cpu;
import com.mycompany.dotcontrolltec.computadores.Disco;
import com.mycompany.dotcontrolltec.computadores.Grafico;
import com.mycompany.dotcontrolltec.computadores.InformacoesSistema;
import com.mycompany.dotcontrolltec.computadores.Ram;
import com.mycompany.exemplo.bd.*;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.List;
import javax.swing.JPanel;
import java.io.IOException;
import java.time.LocalDate;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.json.JSONObject;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import org.springframework.jdbc.core.BeanPropertyRowMapper;
import org.springframework.jdbc.core.JdbcTemplate;
import oshi.SystemInfo;
import oshi.software.os.OSProcess;

/**
 *
 * @author Aluno
 */
public class TelaPrincipal extends javax.swing.JFrame {
   
        
        String NomeProcesso;
    Integer contador = 0;
    
    Integer contador2 = 0;
    Integer contador3 = 0;
    Double usoCpu;
    String nomeComputador;
    Integer fkComputador = 0, fkRam, fkCpu,fkDisco;

    Cpu cpu = new Cpu();
    Ram ram = new Ram();
    Disco disco = new Disco();
    Grafico grafico = new Grafico();
    SystemInfo si = new SystemInfo();
    Conection config = new Conection();
    JdbcTemplate con = new JdbcTemplate(config.getDatasource());
    InformacoesSistema infosis = new InformacoesSistema();
     Powershell powershell = new Powershell();
    Slack slack = new Slack();
    
    DefaultCategoryDataset dadosCpu = new DefaultCategoryDataset();
    DefaultPieDataset dadosRam = new DefaultPieDataset();
    DefaultPieDataset dadosDisco = new DefaultPieDataset();
    //loops temporizadores
    Timer timerCpu;
    private final Tecnico tecnico;

    /**
     * Creates new form TelaPrincipal
     * @param tecnico
     * @param fkCpu
     * @param fkDisco
     * @param fkRam
     */
    public TelaPrincipal(Tecnico tecnico,Integer fkCpu, Integer fkDisco,Integer fkRam) {
        this.timerCpu = new Timer(1000, acaoRam);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.tecnico = tecnico;
        this.fkCpu = fkCpu;
        this.fkDisco = fkDisco;
        this.fkRam = fkRam;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollBar1 = new javax.swing.JScrollBar();
        jpMenu = new javax.swing.JPanel();
        jpMenuCpu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jpMenuRam = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jpMenuInformacoes = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jpMenuDisco = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jpMenuProcessos = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jpTela = new javax.swing.JPanel();
        jpTelaDisco = new javax.swing.JPanel();
        jpGraficoDisco = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        lblDiscoNome = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lblDiscoLivre = new javax.swing.JLabel();
        lblDiscouso = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jpTelaInformacoes = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        lblSistemaSo = new javax.swing.JLabel();
        lblSistemaVersao = new javax.swing.JLabel();
        lblSistemaSerialNumber = new javax.swing.JLabel();
        jpTelaCpu = new javax.swing.JPanel();
        jpGraficoCpu = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblCpuNome = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblTemperaturaCpu = new javax.swing.JLabel();
        lblQtdProcessos = new javax.swing.JLabel();
        lblCpuBits = new javax.swing.JLabel();
        lblFrequenciaMaxima = new javax.swing.JLabel();
        lblFrequenciaAtual = new javax.swing.JLabel();
        lblUsoCpu = new javax.swing.JLabel();
        jpTelaRam = new javax.swing.JPanel();
        jpGraficoRam = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        lblRamTipoMemoria = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblRamPorcentagemUso = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblRamUso = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblRamLivre = new javax.swing.JLabel();
        lblRamTotal = new javax.swing.JLabel();
        jpTelaInicio = new javax.swing.JPanel();
        jpTelaProcessos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProcesses = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        lblTecnicoNome = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        lblTecnicoTelefone = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 654, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jpMenu.setBackground(new java.awt.Color(255, 255, 255));
        jpMenu.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        jpMenuCpu.setBackground(new java.awt.Color(204, 204, 255));
        jpMenuCpu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpMenuCpuMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CPU");

        javax.swing.GroupLayout jpMenuCpuLayout = new javax.swing.GroupLayout(jpMenuCpu);
        jpMenuCpu.setLayout(jpMenuCpuLayout);
        jpMenuCpuLayout.setHorizontalGroup(
            jpMenuCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpMenuCpuLayout.setVerticalGroup(
            jpMenuCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );

        jpMenuRam.setBackground(new java.awt.Color(204, 204, 255));
        jpMenuRam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpMenuRamMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("RAM");

        javax.swing.GroupLayout jpMenuRamLayout = new javax.swing.GroupLayout(jpMenuRam);
        jpMenuRam.setLayout(jpMenuRamLayout);
        jpMenuRamLayout.setHorizontalGroup(
            jpMenuRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpMenuRamLayout.setVerticalGroup(
            jpMenuRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );

        jpMenuInformacoes.setBackground(new java.awt.Color(204, 204, 255));
        jpMenuInformacoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpMenuInformacoesMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Informações do sistema");

        javax.swing.GroupLayout jpMenuInformacoesLayout = new javax.swing.GroupLayout(jpMenuInformacoes);
        jpMenuInformacoes.setLayout(jpMenuInformacoesLayout);
        jpMenuInformacoesLayout.setHorizontalGroup(
            jpMenuInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpMenuInformacoesLayout.setVerticalGroup(
            jpMenuInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
        );

        jpMenuDisco.setBackground(new java.awt.Color(204, 204, 255));
        jpMenuDisco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpMenuDiscoMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DISCO");

        javax.swing.GroupLayout jpMenuDiscoLayout = new javax.swing.GroupLayout(jpMenuDisco);
        jpMenuDisco.setLayout(jpMenuDiscoLayout);
        jpMenuDiscoLayout.setHorizontalGroup(
            jpMenuDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpMenuDiscoLayout.setVerticalGroup(
            jpMenuDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText(".ControlTec");

        jPanel6.setBackground(new java.awt.Color(0, 51, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jpMenuProcessos.setBackground(new java.awt.Color(204, 204, 255));
        jpMenuProcessos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpMenuProcessosMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("PROCESSOS");

        javax.swing.GroupLayout jpMenuProcessosLayout = new javax.swing.GroupLayout(jpMenuProcessos);
        jpMenuProcessos.setLayout(jpMenuProcessosLayout);
        jpMenuProcessosLayout.setHorizontalGroup(
            jpMenuProcessosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 242, Short.MAX_VALUE)
            .addGroup(jpMenuProcessosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE))
        );
        jpMenuProcessosLayout.setVerticalGroup(
            jpMenuProcessosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
            .addGroup(jpMenuProcessosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpMenuLayout = new javax.swing.GroupLayout(jpMenu);
        jpMenu.setLayout(jpMenuLayout);
        jpMenuLayout.setHorizontalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMenuCpu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpMenuRam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpMenuInformacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpMenuDisco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMenuLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(23, 23, 23))
            .addComponent(jpMenuProcessos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpMenuLayout.setVerticalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpMenuCpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpMenuRam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpMenuDisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpMenuInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpMenuProcessos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpTela.setBackground(new java.awt.Color(255, 255, 255));

        jpTelaDisco.setBackground(new java.awt.Color(255, 255, 255));
        jpTelaDisco.setPreferredSize(new java.awt.Dimension(8, 8));

        javax.swing.GroupLayout jpGraficoDiscoLayout = new javax.swing.GroupLayout(jpGraficoDisco);
        jpGraficoDisco.setLayout(jpGraficoDiscoLayout);
        jpGraficoDiscoLayout.setHorizontalGroup(
            jpGraficoDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jpGraficoDiscoLayout.setVerticalGroup(
            jpGraficoDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 176, Short.MAX_VALUE)
        );

        jLabel20.setText("Disco");

        lblDiscoNome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDiscoNome.setText("...");
        lblDiscoNome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel21.setText("Disco livre:");

        jLabel22.setText("Disco em uso:");

        jLabel23.setText("Disco total:");

        lblDiscoLivre.setText("...");

        lblDiscouso.setText("...");

        jLabel24.setText("...");

        javax.swing.GroupLayout jpTelaDiscoLayout = new javax.swing.GroupLayout(jpTelaDisco);
        jpTelaDisco.setLayout(jpTelaDiscoLayout);
        jpTelaDiscoLayout.setHorizontalGroup(
            jpTelaDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTelaDiscoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jpTelaDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpTelaDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel20)
                        .addComponent(jpGraficoDisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblDiscoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpTelaDiscoLayout.createSequentialGroup()
                        .addGroup(jpTelaDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(lblDiscoLivre, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(91, 91, 91)
                        .addGroup(jpTelaDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDiscouso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(87, 87, 87)
                        .addGroup(jpTelaDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jpTelaDiscoLayout.setVerticalGroup(
            jpTelaDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTelaDiscoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDiscoNome)
                .addGap(18, 18, 18)
                .addComponent(jpGraficoDisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpTelaDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpTelaDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiscoLivre)
                    .addComponent(lblDiscouso)
                    .addComponent(jLabel24))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        jpTelaInformacoes.setBackground(new java.awt.Color(255, 255, 255));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel25.setText("Informações do sistema");

        jLabel26.setText("Sistema Operacional:");

        jLabel27.setText("Versão:");

        jLabel28.setText("SerialNumber:");

        lblSistemaSo.setText("...");

        lblSistemaVersao.setText("...");

        lblSistemaSerialNumber.setText("...");

        javax.swing.GroupLayout jpTelaInformacoesLayout = new javax.swing.GroupLayout(jpTelaInformacoes);
        jpTelaInformacoes.setLayout(jpTelaInformacoesLayout);
        jpTelaInformacoesLayout.setHorizontalGroup(
            jpTelaInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTelaInformacoesLayout.createSequentialGroup()
                .addGroup(jpTelaInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpTelaInformacoesLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel25))
                    .addGroup(jpTelaInformacoesLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jpTelaInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpTelaInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSistemaSo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSistemaVersao, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(lblSistemaSerialNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jpTelaInformacoesLayout.setVerticalGroup(
            jpTelaInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTelaInformacoesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel25)
                .addGap(32, 32, 32)
                .addGroup(jpTelaInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(lblSistemaSo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpTelaInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(lblSistemaVersao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpTelaInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(lblSistemaSerialNumber))
                .addContainerGap(272, Short.MAX_VALUE))
        );

        jpTelaCpu.setBackground(new java.awt.Color(255, 255, 255));
        jpTelaCpu.setPreferredSize(new java.awt.Dimension(8, 8));

        javax.swing.GroupLayout jpGraficoCpuLayout = new javax.swing.GroupLayout(jpGraficoCpu);
        jpGraficoCpu.setLayout(jpGraficoCpuLayout);
        jpGraficoCpuLayout.setHorizontalGroup(
            jpGraficoCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
        );
        jpGraficoCpuLayout.setVerticalGroup(
            jpGraficoCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 213, Short.MAX_VALUE)
        );

        jLabel6.setText("CPU");

        lblCpuNome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCpuNome.setText("...");

        jLabel7.setText("Temperatura:");

        jLabel8.setText("quantidade de processos:");

        jLabel10.setText("% de uso:");

        jLabel11.setText("Suporta 64 bits?");

        jLabel12.setText("Frequencia atual:");

        jLabel13.setText("Frequencia maxima:");

        lblTemperaturaCpu.setText("...");

        lblQtdProcessos.setText("...");

        lblCpuBits.setText("...");

        lblFrequenciaMaxima.setText("...");

        lblFrequenciaAtual.setText("...");

        lblUsoCpu.setText("...");

        javax.swing.GroupLayout jpTelaCpuLayout = new javax.swing.GroupLayout(jpTelaCpu);
        jpTelaCpu.setLayout(jpTelaCpuLayout);
        jpTelaCpuLayout.setHorizontalGroup(
            jpTelaCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTelaCpuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpTelaCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCpuNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
            .addGroup(jpTelaCpuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpTelaCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblFrequenciaMaxima, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTemperaturaCpu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpTelaCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jpTelaCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblQtdProcessos, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addComponent(lblFrequenciaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jpTelaCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10)
                    .addComponent(lblCpuBits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUsoCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jpTelaCpuLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jpGraficoCpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jpTelaCpuLayout.setVerticalGroup(
            jpTelaCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTelaCpuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCpuNome)
                .addGap(26, 26, 26)
                .addComponent(jpGraficoCpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpTelaCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTelaCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpTelaCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTemperaturaCpu)
                    .addComponent(lblQtdProcessos)
                    .addComponent(lblCpuBits))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpTelaCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpTelaCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFrequenciaMaxima)
                    .addComponent(lblFrequenciaAtual)
                    .addComponent(lblUsoCpu))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jpTelaRam.setBackground(new java.awt.Color(255, 255, 255));
        jpTelaRam.setPreferredSize(new java.awt.Dimension(474, 417));

        javax.swing.GroupLayout jpGraficoRamLayout = new javax.swing.GroupLayout(jpGraficoRam);
        jpGraficoRam.setLayout(jpGraficoRamLayout);
        jpGraficoRamLayout.setHorizontalGroup(
            jpGraficoRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );
        jpGraficoRamLayout.setVerticalGroup(
            jpGraficoRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 184, Short.MAX_VALUE)
        );

        jLabel15.setText("Ram");

        lblRamTipoMemoria.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRamTipoMemoria.setText("...");

        jLabel16.setText("% de uso:");

        lblRamPorcentagemUso.setText("...");

        jLabel17.setText("Memoria em uso:");

        lblRamUso.setText("...");

        jLabel18.setText("Memoria Livre:");

        jLabel19.setText("Memorira total:");

        lblRamLivre.setText("...");

        lblRamTotal.setText("...");

        javax.swing.GroupLayout jpTelaRamLayout = new javax.swing.GroupLayout(jpTelaRam);
        jpTelaRam.setLayout(jpTelaRamLayout);
        jpTelaRamLayout.setHorizontalGroup(
            jpTelaRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTelaRamLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(jpTelaRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblRamLivre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16)
                    .addComponent(lblRamPorcentagemUso, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpTelaRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRamUso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRamTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(132, 132, 132))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTelaRamLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jpTelaRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpGraficoRam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRamTipoMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(22, 22, 22))
        );
        jpTelaRamLayout.setVerticalGroup(
            jpTelaRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTelaRamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRamTipoMemoria)
                .addGap(20, 20, 20)
                .addComponent(jpGraficoRam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpTelaRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpTelaRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRamPorcentagemUso)
                    .addComponent(lblRamUso))
                .addGap(18, 18, 18)
                .addGroup(jpTelaRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(jpTelaRamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRamLivre)
                    .addComponent(lblRamTotal))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jpTelaInicio.setBackground(new java.awt.Color(0, 204, 153));

        javax.swing.GroupLayout jpTelaInicioLayout = new javax.swing.GroupLayout(jpTelaInicio);
        jpTelaInicio.setLayout(jpTelaInicioLayout);
        jpTelaInicioLayout.setHorizontalGroup(
            jpTelaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );
        jpTelaInicioLayout.setVerticalGroup(
            jpTelaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
        );

        jpTelaProcessos.setBackground(new java.awt.Color(255, 255, 255));

        tblProcesses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPU", "Memory"
            }
        ));
        jScrollPane1.setViewportView(tblProcesses);

        javax.swing.GroupLayout jpTelaProcessosLayout = new javax.swing.GroupLayout(jpTelaProcessos);
        jpTelaProcessos.setLayout(jpTelaProcessosLayout);
        jpTelaProcessosLayout.setHorizontalGroup(
            jpTelaProcessosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
        );
        jpTelaProcessosLayout.setVerticalGroup(
            jpTelaProcessosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpTelaLayout = new javax.swing.GroupLayout(jpTela);
        jpTela.setLayout(jpTelaLayout);
        jpTelaLayout.setHorizontalGroup(
            jpTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
            .addGroup(jpTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpTelaProcessos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpTelaLayout.createSequentialGroup()
                    .addComponent(jpTelaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jpTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpTelaInformacoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpTelaRam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpTelaCpu, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE))
            .addGroup(jpTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpTelaDisco, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE))
        );
        jpTelaLayout.setVerticalGroup(
            jpTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jpTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpTelaProcessos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpTelaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpTelaInformacoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpTelaRam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpTelaCpu, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE))
            .addGroup(jpTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpTelaDisco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel14.setText("Perfil usuario");

        jLabel29.setText("Nome:");

        lblTecnicoNome.setText("...");

        jLabel31.setText("Telefone:");

        lblTecnicoTelefone.setText("...");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTecnicoNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTecnicoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(lblTecnicoNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(lblTecnicoTelefone))
                .addContainerGap(316, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpTela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpTela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpMenuCpuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpMenuCpuMouseClicked
        trocaCor(jpMenuCpu, jpMenuRam, jpMenuDisco, jpMenuInformacoes, jpMenuProcessos);
        trocaAba(jpTelaCpu, jpTelaRam, jpTelaDisco, jpTelaInformacoes, jpTelaProcessos, jpTelaInicio);

    }//GEN-LAST:event_jpMenuCpuMouseClicked

    private void jpMenuRamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpMenuRamMouseClicked
        trocaCor(jpMenuRam, jpMenuDisco, jpMenuCpu, jpMenuInformacoes, jpMenuProcessos);
        trocaAba(jpTelaRam, jpTelaCpu, jpTelaDisco, jpTelaInformacoes, jpTelaProcessos, jpTelaInicio);


    }//GEN-LAST:event_jpMenuRamMouseClicked

    private void jpMenuDiscoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpMenuDiscoMouseClicked
        trocaCor(jpMenuDisco, jpMenuCpu, jpMenuInformacoes, jpMenuProcessos, jpMenuRam);
        trocaAba(jpTelaDisco, jpTelaRam, jpTelaCpu, jpTelaInformacoes, jpTelaProcessos, jpTelaInicio);
    }//GEN-LAST:event_jpMenuDiscoMouseClicked

    private void jpMenuInformacoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpMenuInformacoesMouseClicked
        // TODO add your handling code here:
        trocaCor(jpMenuInformacoes, jpMenuDisco, jpMenuCpu, jpMenuProcessos, jpMenuRam);
        trocaAba(jpTelaInformacoes, jpTelaDisco, jpTelaRam, jpTelaCpu, jpTelaProcessos, jpTelaInicio);
    }//GEN-LAST:event_jpMenuInformacoesMouseClicked

    private void jpMenuProcessosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpMenuProcessosMouseClicked
        // TODO add your handling code here:
        trocaCor(jpMenuProcessos, jpMenuInformacoes, jpMenuDisco, jpMenuCpu, jpMenuRam);
        trocaAba(jpTelaProcessos, jpTelaInformacoes, jpTelaDisco, jpTelaRam, jpTelaCpu, jpTelaInicio);
    }//GEN-LAST:event_jpMenuProcessosMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //Quando o jframe abre
        exibeInfoSistema();
        exibePerfil();
        trocaAba(jpTelaInicio, jpTelaDisco, jpTelaRam, jpTelaCpu, jpTelaInformacoes, jpTelaProcessos);
        String select = "select * from Computador where serialnum = ? and fkEscola = ?;";
        List<Computador> dadosComp = con.query(select,new BeanPropertyRowMapper(Computador.class),infosis.serialPlacaMae(),tecnico.getFkEscola());
        nomeComputador = dadosComp.get(0).getNomeComputador();
//  
//        
        for(Computador c : dadosComp){
            fkComputador = c.getIdComputador();
        };
        con.update("update computador set disponibilidade = 1 where idComputador = ?", fkComputador);
        ActionListener acao = (ActionEvent executar) -> {
            try {
                //tela CPU
                exibeDadosCpu();
            } catch (Exception ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                //tela RAM
                exibeDadosRam();
            } catch (Exception ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }

            try {
                //tela disco
                exibeDisco();
                //inserindo os dados
            } catch (Exception ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
                    //tela processos
            exibeProcessos();
            try {
                encerraProcesso();
            } catch (IOException ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }


        };
        Timer tempo = new Timer(7000, acao);

        //iniciar o temporizador
        tempo.start();

    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        //atualizando status de disponibilizade para false
        con.update("update computador set disponibilidade = 0 where idComputador = ?", fkComputador);
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        con.update("update computador set disponibilidade = 0 where idComputador = ?", fkComputador);
    }//GEN-LAST:event_formWindowClosing
    ActionListener acaoRam = ((arg0) -> {
        try {
                
                exibeDadosRam();
            } catch (Exception ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
    });
    /**
     * @param args the command line arguments
     */


    public void trocaCor(JPanel troca, JPanel mantem1, JPanel mantem2, JPanel mantem3, JPanel mantem4) {
        troca.setBackground(new Color(51, 51, 255));
        mantem1.setBackground(new Color(204, 204, 255));
        mantem2.setBackground(new Color(204, 204, 255));
        mantem3.setBackground(new Color(204, 204, 255));
        mantem4.setBackground(new Color(204, 204, 255));
    }

    public void trocaAba(JPanel exibe, JPanel oculta1, JPanel oculta2, JPanel oculta3, JPanel oculta4, JPanel oculta5) {
        exibe.setVisible(true);
        oculta1.setVisible(false);
        oculta2.setVisible(false);
        oculta3.setVisible(false);
        oculta4.setVisible(false);
        oculta5.setVisible(false);

    }
    


    private void exibeDadosCpu() throws Exception{
        Integer hora = LocalTime.now().getHour();
        Integer minuto= LocalTime.now().getMinute();
        Integer segundo = LocalTime.now().getSecond();
        String horario = String.format("%d:%d:%d", hora, minuto,segundo);
        if(segundo < 10){
             horario = String.format("%d:%d:0%d", hora, minuto,segundo);
        }
        
        usoCpu = cpu.porcetagemDeUso();
        lblFrequenciaAtual.setText(String.format("%.2f GHz", cpu.frenquenciaCpu()));
        lblFrequenciaMaxima.setText(String.format("%.2f GHz", cpu.frequenciaMax()));
        lblQtdProcessos.setText(cpu.quantidadeProcessos().toString());
        lblUsoCpu.setText(String.format("%.2f%%", usoCpu));
        lblTemperaturaCpu.setText(String.format("%.2f°C", cpu.Temperatura()));
        lblCpuBits.setText(cpu.bits());
        lblCpuNome.setText(cpu.nome());
        powershell.encerraProcesso();
        
        if(usoCpu > 90.0){
            String select = "select * from Alerta where fkComputador = ? and  tipoAlerta = 2 and componenteAlerta = 1;";
            List<Computador> alertaJaInserido = con.query(select,new BeanPropertyRowMapper(Alerta.class), fkComputador);
            if(alertaJaInserido.isEmpty()) {
                con.update("insert into Alerta (tituloAlerta, tipoAlerta, componenteAlerta, descricaoAlerta, fkComputador, dataHora) values(?,?,?,?,?,?)",
                        "Alto uso de CPU",
                        2,
                        1,
                        "Uso de CPU está em: " + usoCpu.intValue() + "%",
                        fkComputador,
                        LocalDateTime.now());
            }
            Slack slack = new Slack();
            JSONObject json = new JSONObject();

            json.put("text", "------Alerta Vermelho------\n"+"IDComputador: "+fkComputador +"\nUso de Cpu: " + usoCpu.intValue() + "%\n" + " Data: " + LocalDate.now() + "\n Hora: "+ LocalTime.now());

            //slack.sendMessage(json);
        }
        
        if(usoCpu < 90.0 && usoCpu > 80.0){
            String select = "select * from Alerta where fkComputador = ? and  tipoAlerta = 1 and componenteAlerta = 1;";
            List<Computador> alertaJaInserido = con.query(select,new BeanPropertyRowMapper(Alerta.class), fkComputador);
            if(alertaJaInserido.isEmpty()) {
                con.update("insert into Alerta (tituloAlerta, tipoAlerta, componenteAlerta, descricaoAlerta, fkComputador, dataHora) values(?,?,?,?,?,?)",
                        "Alto uso de CPU",
                        1,
                        1,
                        "Uso de CPU está em: " + usoCpu.intValue() + "%",
                        fkComputador,
                        LocalDateTime.now());
            }
            Slack slack = new Slack();
            JSONObject json = new JSONObject();

            json.put("text", "------Alerta Amarelo------\n"+"IDComputador: "+fkComputador +"\nUso de Cpu: " + usoCpu.intValue() + "%\n" + " Data: " + LocalDate.now() + "\n Hora: "+ LocalTime.now());

            //slack.sendMessage(json);
            System.out.println("teste " + json);
        }
        
        dadosCpu.addValue(usoCpu, "Uso da cpu", horario);
        contador++;
        if (contador.equals(6)) {
            dadosCpu.removeColumn(0);
            contador--;

        }
        grafico.GraficoLinha(dadosCpu, "CPU","Hora", "% de uso", jpGraficoCpu);
        con.update("insert into UsoTotal (usoComponente, dataHora, fkComponente) values(?,?,?)", usoCpu,LocalDateTime.now(), fkCpu);
        
        

    }

    private void exibeDadosRam() throws Exception {
        lblRamUso.setText(String.format("%.2fGB", ram.qtdMemoriaRamUsada()));
        lblRamLivre.setText(String.format("%.2fGB", ram.qtdMemoriaRamLivre()));
        lblRamTotal.setText(String.format("%.2fGB", ram.qtdMemoriaRamTotal()));
        lblRamPorcentagemUso.setText(String.format("%.1f%%", ram.porcetagemDeMemoria()));
        lblRamTipoMemoria.setText(ram.tipoMemoria());

        Double usoRam = ram.qtdMemoriaRamUsada();
        Double espacoLivre = ram.qtdMemoriaRamLivre();
        dadosRam.setValue("em uso", usoRam);
        dadosRam.setValue("livre", espacoLivre);
        
        grafico.GraficoDunuts(dadosRam, "Ram", jpGraficoRam);
        con.update("insert into UsoTotal (usoComponente, dataHora, fkComponente) values(?,?,?)",ram.porcetagemDeMemoria(),LocalDateTime.now() , fkRam);

        
        if(ram.porcetagemDeMemoria() > 90.0){
            String select = "select * from Alerta where fkComputador = ? and  tipoAlerta = 2 and componenteAlerta = 2;";
            List<Computador> alertaJaInserido = con.query(select,new BeanPropertyRowMapper(Alerta.class), fkComputador);
            if(alertaJaInserido.isEmpty()) {
                con.update("insert into Alerta (tituloAlerta, tipoAlerta, componenteAlerta, descricaoAlerta, fkComputador, dataHora) values(?,?,?,?,?,?)",
                        "Alto uso de memória",
                        2,
                        2,
                        "Uso de memória está em: " + ram.porcetagemDeMemoria().intValue() + "%",
                        fkComputador,
                        LocalDateTime.now());
            }

            Slack slack = new Slack();
            JSONObject json = new JSONObject();

            json.put("text", "------Alerta Vermelho------\n"+"IDComputador: "+fkComputador +"\nUso de Ram: " + ram.porcetagemDeMemoria().intValue() + "%\n" + " Data: " + LocalDate.now() + "\n Hora: "+ LocalTime.now());

           // slack.sendMessage(json);
        }
        
        if(ram.porcetagemDeMemoria() < 90.0 && ram.porcetagemDeMemoria() > 80.0){
            String select = "select * from Alerta where fkComputador = ? and  tipoAlerta = 1 and componenteAlerta = 2;";
            List<Computador> alertaJaInserido = con.query(select,new BeanPropertyRowMapper(Alerta.class), fkComputador);
            if(alertaJaInserido.isEmpty()) {
                con.update("insert into Alerta (tituloAlerta, tipoAlerta, componenteAlerta, descricaoAlerta, fkComputador, dataHora) values(?,?,?,?,?,?)",
                        "Elevado uso de memória",
                        1,
                        2,
                        "Uso de memória está em: " + ram.porcetagemDeMemoria().intValue() + "%",
                        fkComputador,
                        LocalDateTime.now());
            }

            Slack slack = new Slack();
            JSONObject json = new JSONObject();

            json.put("text", "------Alerta Amarelo------\n"+"IDComputador: "+fkComputador +"\nUso de Ram: " + ram.porcetagemDeMemoria().intValue() + "%\n" + " Data: " + LocalDate.now() + "\n Hora: "+ LocalTime.now());

           // slack.sendMessage(json);
            System.out.println("teste " + json);
        }
    }
    public void exibeDisco() throws Exception{
        jLabel24.setText(String.format("%.2fGB", disco.qtdEspacoTotalDisco()));
        lblDiscoLivre.setText(String.format("%.2fGB", disco.qtdEspacoLivre()));
        lblDiscouso.setText(String.format("%.2fGB", disco.qtdEspacoUsadoDisco()));
        lblDiscoNome.setText(disco.nome());
        dadosDisco.setValue("em uso", disco.qtdEspacoUsadoDisco());
        dadosDisco.setValue("Livre", disco.qtdEspacoLivre());
        grafico.GraficoDunuts(dadosDisco, "uso disco", jpGraficoDisco);
//        
        con.update("insert into UsoTotal (usoComponente, dataHora, fkComponente) values(?,?,?)",disco.porcetagemDisco(),LocalDateTime.now() , fkDisco);
        
        if(disco.porcetagemDisco() > 90.0){
        Slack slack = new Slack();
        JSONObject json = new JSONObject();
        
        json.put("text", "------Alerta Vermelho------\n"+"IDComputador: "+fkComputador +"\nUso de Disco: " + ram.porcetagemDeMemoria().intValue() + "%\n" + " Data: " + LocalDate.now() + "\n Hora: "+ LocalTime.now());
        
        // slack.sendMessage(json); TIREI PORQUE ESSA BOMBA PODE NEM ESTAR FUNCIONANDO MAIS
        }
        
        if(disco.porcetagemDisco() < 90.0 && disco.porcetagemDisco() > 80.0){
        Slack slack = new Slack();
        JSONObject json = new JSONObject();
        
        json.put("text", "------Alerta Amarelo------\n"+"IDComputador: "+fkComputador +"\nUso de Disco: " + ram.porcetagemDeMemoria().intValue() + "%\n" + " Data: " + LocalDate.now() + "\n Hora: "+ LocalTime.now());
      
       //slack.sendMessage(json);
        System.out.println("teste " + json);
        }
    }
    public void exibePerfil(){
        lblTecnicoNome.setText(tecnico.getNomeTecnico());
        lblTecnicoTelefone.setText(tecnico.getTelefoneTec());
//        jLabel34.setText(nomeComputador);
    }
     public void encerraProcesso() throws IOException {
        Integer contador4 = 0;

        String select1 = "select * from Computador where serialnum = ? and fkEscola = ?;";
        List<Computador> dadosComp = con.query(select1,new BeanPropertyRowMapper(Computador.class),infosis.serialPlacaMae(),tecnico.getFkEscola());
        for(Computador c : dadosComp){
            fkComputador = c.getIdComputador();
        };

        String select = "SELECT b.nomeProcesso FROM Computador_has_Blacklist ch JOIN Computador c ON ch.fkComputador = c.idComputador JOIN Blacklist b ON ch.fkBlacklist = b.idBlacklist WHERE c.idComputador = ?;";
        List<Blacklist> SelectProcesso = con.query(select,new BeanPropertyRowMapper(Blacklist.class),fkComputador);

        
        if(!SelectProcesso.isEmpty()){
            for (Blacklist blacklist : SelectProcesso) {
                NomeProcesso = SelectProcesso.get(contador4).getNomeProcesso();
                
                System.out.println(SelectProcesso.get(contador4).getNomeProcesso());
                
                Scanner scn = new Scanner(System.in);
                //String command2 = "get-process";
                String command1 = "powershell.exe ";

                String teste = NomeProcesso ;

                String command10 = "Stop-Process  -name " + teste;
                //DESINTALAR COMANDO POWERSHELL

                Process powerShellProcess = Runtime.getRuntime().exec(command1 + command10);

                System.out.println("Feito");
                contador4++;
            }
        
        }
     }

    public void exibeProcessos() {
        DefaultTableModel model = (DefaultTableModel) tblProcesses.getModel();

        Integer cpuCount = si.getHardware().getProcessor().getLogicalProcessorCount();
        Long totalMem = si.getHardware().getMemory().getTotal();
        model.setRowCount(0);

        for (OSProcess process : si.getOperatingSystem().getProcesses()) {

            if (process.getProcessID() > 0) {
                model.addRow(new Object[]{
                    process.getProcessID(),
                    process.getName(),
                    String.format("%.1f%%", 100.0 * process.getProcessCpuLoadCumulative() / cpuCount),
                    String.format("%.1f%%", 100.0 * process.getResidentSetSize() / totalMem)
                });
                 Double porcentagemMemoria = 100.0 * process.getResidentSetSize() / totalMem;
                 
                // con.update("insert into Processo values(?,?,?,?,?)",process.getName(),LocalDateTime.now(),porcentagemMemoria,fkComputador, process.getProcessID());

            }

        }
        
    }
    public void exibeInfoSistema(){
        lblSistemaSo.setText(infosis.sistemaOperacional());
        lblSistemaSerialNumber.setText(infosis.serialPlacaMae());
    }
    public static void main(String[] args) {
        new TelaPrincipal(new Tecnico(),1,1,1).setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpGraficoCpu;
    private javax.swing.JPanel jpGraficoDisco;
    private javax.swing.JPanel jpGraficoRam;
    private javax.swing.JPanel jpMenu;
    private javax.swing.JPanel jpMenuCpu;
    private javax.swing.JPanel jpMenuDisco;
    private javax.swing.JPanel jpMenuInformacoes;
    private javax.swing.JPanel jpMenuProcessos;
    private javax.swing.JPanel jpMenuRam;
    private javax.swing.JPanel jpTela;
    private javax.swing.JPanel jpTelaCpu;
    private javax.swing.JPanel jpTelaDisco;
    private javax.swing.JPanel jpTelaInformacoes;
    private javax.swing.JPanel jpTelaInicio;
    private javax.swing.JPanel jpTelaProcessos;
    private javax.swing.JPanel jpTelaRam;
    private javax.swing.JLabel lblCpuBits;
    private javax.swing.JLabel lblCpuNome;
    private javax.swing.JLabel lblDiscoLivre;
    private javax.swing.JLabel lblDiscoNome;
    private javax.swing.JLabel lblDiscouso;
    private javax.swing.JLabel lblFrequenciaAtual;
    private javax.swing.JLabel lblFrequenciaMaxima;
    private javax.swing.JLabel lblQtdProcessos;
    private javax.swing.JLabel lblRamLivre;
    private javax.swing.JLabel lblRamPorcentagemUso;
    private javax.swing.JLabel lblRamTipoMemoria;
    private javax.swing.JLabel lblRamTotal;
    private javax.swing.JLabel lblRamUso;
    private javax.swing.JLabel lblSistemaSerialNumber;
    private javax.swing.JLabel lblSistemaSo;
    private javax.swing.JLabel lblSistemaVersao;
    private javax.swing.JLabel lblTecnicoNome;
    private javax.swing.JLabel lblTecnicoTelefone;
    private javax.swing.JLabel lblTemperaturaCpu;
    private javax.swing.JLabel lblUsoCpu;
    private javax.swing.JTable tblProcesses;
    // End of variables declaration//GEN-END:variables
}
